name: Format Check (Bun)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
        cache: true
    
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        working-dir: frontend
    
    - name: Check Rust formatting - backend
      run: |
        cd backend
        cargo fmt -- --check
    
    - name: Check Rust formatting - tauri
      run: |
        cd frontend/tauri-app/src-tauri
        cargo fmt -- --check
    
    - name: Check biome formatting
      run: |
        cd frontend
        biome format
